# This is the profile configuration file for local execution.

# To run the workflow with local execution use the following command:
# snakemake --profile config/default

# Config you can change
cores: 10
keep-going: False
rerun-incomplete: True
printshellcmds: True
dry-run: False
conda-frontend: mamba

# Config you should not change unless you know what you are doing
use-conda: True
use-apptainer: True
apptainer-args: "--bind $(pwd):$(pwd)"