---
title: "Normalization of Chromosomal Depth"
author: "Claudia Zirión-Martínez"
date: "2025-04-18"

fig-height: 7
fig-width: 9
---
## Setup {#setup}

```{r, eval=FALSE, echo=FALSE}
setwd("/FastData/czirion/WeavePop_Cneoformans/analyses")
```

Libraries

```{r libraries, output=FALSE}
library(tidyverse)
library(patchwork)
library(ggbeeswarm)
library(ggnewscale)
library(RColorBrewer)
library(hexbin)
library(ggExtra)
library(ggrepel)
```

Paths

```{r paths}
chromosomes_path <-
    "../Crypto_Desjardins/results/04.Intermediate_files/03.References/chromosome_lengths.tsv"
depth_by_chrom_good_desj_path <-
    "../Crypto_Desjardins/results/04.Intermediate_files/02.Dataset/depth_quality/depth_by_chrom_good.tsv"
depth_by_chrom_good_ashton_path <-
    "../Crypto_Ashton/results/04.Intermediate_files/02.Dataset/depth_quality/depth_by_chrom_good.tsv"
```

### Chromosome names and length {#chromosome-names-and-length}

Get the nice chromosome names from the chromosomes file in WeavePop.

```{r}
chromosomes = read.delim(
    chromosomes_path,
    header=TRUE, sep=",") %>%
    mutate(chromosome = str_pad(chromosome, 2, pad = "0"))%>%
    mutate(chromosome = as.factor(chromosome))
levels(chromosomes$chromosome) <- paste("chr", chromosomes$chromosome, sep="")
```

## Chromosome depth

```{r}
depth_by_chrom_good_desjardins <- read.delim(
    depth_by_chrom_good_desj_path,
     header=TRUE, sep="\t")
depth_by_chrom_good_ashton <- read.delim(
    depth_by_chrom_good_ashton_path,
     header=TRUE, sep="\t")
depth_by_chrom <- rbind(depth_by_chrom_good_desjardins, depth_by_chrom_good_ashton)
```

### Normalize the depth by all the global metrics

```{r}
depth_by_chrom_new <- depth_by_chrom %>%
  left_join(chromosomes, by = "accession") %>%
  select(sample, lineage, length, accession, chromosome, starts_with("chrom"), starts_with("global_"))%>%
  mutate(norm_median_by_median = round(chrom_median / global_median,2),
        norm_mean_by_median = round(chrom_mean / global_median,2),
        norm_median_by_mean = round(chrom_median / global_mean,2),
        norm_mean_by_mean = round(chrom_mean / global_mean,2),
        norm_median_by_mode = round(chrom_median / global_mode,2),
        norm_mean_by_mode = round(chrom_mean / global_mode,2)
)
```

```{r, message = FALSE, warning = FALSE}
dd <- ggplot(depth_by_chrom_new, aes(y = norm_median_by_median, x = length, color = chromosome))+
        geom_point(alpha = 0.05)+
        geom_smooth(method = "lm", se = TRUE, color = "blue", linetype = "dashed") +
        geom_hline(yintercept =1, color = "black", linetype = "solid")+
        geom_hline(yintercept =2, color = "black", linetype = "solid")+
        ylim(0,3)+
        theme_minimal() +
        theme(legend.position = "none")+
        labs(title = "Median Normalized\nby Global Median",
            y = "Normalized Depth of Chromosomes",
            x = "Chromosome length")

dm <- ggplot(depth_by_chrom_new, aes(y = norm_median_by_mean, x = length, color = chromosome))+
        geom_point(alpha = 0.05)+
        geom_smooth(method = "lm", se = TRUE, color = "blue", linetype = "dashed") +
        geom_hline(yintercept =1, color = "black", linetype = "solid")+
        geom_hline(yintercept =2, color = "black", linetype = "solid")+
        ylim(0,3)+
        theme_minimal() +
        theme(legend.position = "none")+
        labs(title = "Median Normalized\nby Global Mean",
            y = "Normalized Depth of Chromosomes",
            x = "Chromosome length")

do <- ggplot(depth_by_chrom_new, aes(y = norm_median_by_mode, x = length, color = chromosome))+
        geom_point(alpha = 0.05)+
        geom_smooth(method = "lm", se = TRUE, color = "blue", linetype = "dashed") +
        geom_hline(yintercept =1, color = "black", linetype = "solid")+
        geom_hline(yintercept =2, color = "black", linetype = "solid")+
        ylim(0,3)+
        theme_minimal() +
        theme(legend.position = "right")+
        labs(title = "Median Normalized\nby Global Mode",
            y = "Normalized Depth of Chromosomes",
            x = "Chromosome length")


md <- ggplot(depth_by_chrom_new, aes(y = norm_mean_by_median, x = length, color = chromosome))+
        geom_point(alpha = 0.05)+
        geom_smooth(method = "lm", se = TRUE, color = "blue", linetype = "dashed") +
        geom_hline(yintercept =1, color = "black", linetype = "solid")+
        geom_hline(yintercept =2, color = "black", linetype = "solid")+
        ylim(0,3)+
        theme_minimal() +
        theme(legend.position = "none")+
        labs(title = "Mean Normalized\nby Global Median",
            y = "Normalized Depth of Chromosomes",
            x = "Chromosome length")

mm <- ggplot(depth_by_chrom_new, aes(y = norm_mean_by_mean, x = length, color = chromosome))+
        geom_point(alpha = 0.05)+
        geom_smooth(method = "lm", se = TRUE, color = "blue", linetype = "dashed") +
        geom_hline(yintercept =1, color = "black", linetype = "solid")+
        geom_hline(yintercept =2, color = "black", linetype = "solid")+
        ylim(0,3)+
        theme_minimal() +
        theme(legend.position = "none")+
        labs(title = "Mean Normalized\nby Mean",
            y = "Normalized Depth of Chromosomes",
            x = "Chromosome length")

mo <- ggplot(depth_by_chrom_new, aes(y = norm_mean_by_mode, x = length, color = chromosome))+
        geom_point(alpha = 0.05)+
        geom_smooth(method = "lm", se = TRUE, color = "blue", linetype = "dashed") +
        geom_hline(yintercept =1, color = "black", linetype = "solid")+
        geom_hline(yintercept =2, color = "black", linetype = "solid")+
        ylim(0,3)+
        theme_minimal() +
        theme(legend.position = "right")+
        labs(title = "Mean Normalizedby Mode",
            y = "Normalized Depth of Chromosomes",
            x = "Chromosome length")

```
```{r, message = FALSE, warning = FALSE}
dd | dm | do
```
```{r, message = FALSE, warning = FALSE}
md | mm | mo
```

```{r}
depth_by_chrom_new <- depth_by_chrom_new %>%
    group_by(sample)%>%
    mutate(mean_of_raw_median = mean(chrom_median))%>%
    ungroup()%>%
    mutate(demeaned_median = chrom_median - mean_of_raw_median)
```
```{r, message = FALSE, warning = FALSE}
ggplot(depth_by_chrom_new, aes(y = demeaned_median, x = length, color = sample))+
        geom_point(alpha = 0.05)+
        geom_line(alpha = 0.05)+
        facet_wrap(~lineage, nrow =1, scales = "free_x")+
        #facet_wrap(~ cut(chrom_median, breaks = seq(0, max(chrom_median, na.rm = TRUE), by = 100)), scales = "free_y", ncol = 1)+
        theme_minimal() +
        theme(legend.position = "none")+
        labs(title = "Median",
            y = "Depth of Chromosomes",
            x = "Chromosome length")
```