---
title: "Number of variants in old vs. trimmed data"
author: "Claudia Zirión-Martínez"
date: "2025-02-14"
---

## Setup
```{r, output=FALSE}
library(tidyverse)
library(ggbeeswarm)
```

```{r}
setwd("/mnt/FastData/czirion/Crypto_Diversity_Pipeline/analyses/")
```
Paths
```{r}
desj_counts_path <- "data/processed/snp_counts_desjardins.csv"
desj_counts_old_path <- "data/processed/snp_counts_desjardins_old.csv"

asht_counts_path <- "data/processed/snp_counts_ashton.csv"
asht_counts_old_path <- "data/processed/snp_counts_ashton_old.csv"
```

## Evaluate the number of raw and filtered SNPs before and after cleaning the reads with FastP
```{r}
desj_counts <- read.csv(desj_counts_path, col.names = c("sample", "raw", "filtered"))
desj_counts_old <- read.csv(desj_counts_old_path, col.names = c("sample", "raw", "filtered"))
asht_counts <- read.csv(asht_counts_path, col.names = c("sample", "raw", "filtered"))
asht_counts_old <- read.csv(asht_counts_old_path, col.names = c("sample", "raw", "filtered"))
```

```{r}
desj_counts_joined <- inner_join(desj_counts, desj_counts_old,
                    by = "sample", suffix = c("_clean", "_old"))%>%
                    mutate(raw_diference = raw_old - raw_clean,
                            filtered_difference = filtered_old - filtered_clean,
                            dataset = "Desjardins")
```

```{r}
asht_counts_joined <- inner_join(asht_counts, asht_counts_old,
                    by = "sample", suffix = c("_clean", "_old"))%>%
                    mutate(raw_diference = raw_old - raw_clean,
                            filtered_difference = filtered_old - filtered_clean,
                            dataset = "Ashton")
```

```{r}
counts <- bind_rows(asht_counts_joined,desj_counts_joined)
```

```{r}
ggplot(counts)+
    geom_boxplot(aes(filtered_difference, x = dataset))
``` 
There is one sample with a very high difference of filtered reads.
```{r}
max_filtered_diff <- counts %>%
    filter(filtered_difference == max(filtered_difference, na.rm = TRUE))
max_filtered_diff
```

Filter it out
```{r}
counts <- counts %>%
    filter(filtered_difference != max(filtered_difference, na.rm = TRUE))
```
```{r}
ggplot(counts)+
    geom_quasirandom(aes(filtered_difference, x = dataset))
``` 