# =============================================================================
#   Choose which workflow to run
# =============================================================================

workflow: "join_datasets" # Options: "analysis", "join_datasets"

# =============================================================================
#   Output (for either workflow)
# =============================================================================

project_directory: "Crypto_Desjardins_Ashton/" # Optional: Path of the project directory, relative to FungalPop/. If empty, the working directory is used.
run_id: "exclude" # Optional: Suffix to append to the 'results/' and 'logs/' directories. 

# =============================================================================
#   Parameters for the join_datasets workflow
# =============================================================================
# This workflow joins the results of running the analysis workflow in different datasets. 
# It assumes that if the same lineage is present in the different datasets, 
# the same reference genome was used.

datasets_paths: "Crypto_Desjardins/results,Crypto_Ashton/results" # Commas separated list of paths to the directories with the results of the analysis workflow.
datasets_names: "Desjardins,Ashton" # Commas separated list of names for the datasets, in the same order as the paths.